name: ForceAlignmentCutter
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - ipykernel
  - notebook
  - sox
  - libsndfile
  - swig
  - bzip2
  - libflac
  - bc
  - pip
  - requests
  - pydub
  - torchaudio
  - cuda-toolkit
  - transformers
  - python-dotenv
  - pytest-runner
  - conda-forge::pytorch
  - sentence-transformers
  - sentencepiece
  - yt-dlp
  - ipywidgets
  - montreal-forced-aligner
  - spacy-pkuseg
  - pip:
    - dragonmapper
    - hanziconv
    - faster-whisper
    - fastapi==0.109.0
    - uvicorn[standard]==0.27.0
    - python-multipart==0.0.6
    - aiofiles==23.2.1
